import RankLabelComponent from "@/components/common/RankLabel/RankLabel";
import type { TableColumn } from "@/components/common/Table/Table";
import type { CompanyTableRow } from "@/app/types/types";

/** Storybook 用。画面の columns は useCompanyPage 側で定義 */
export const mockCompanyColumns: TableColumn<CompanyTableRow>[] = [
  { label: "会社名", key: "clientName" },
  { label: "営業担当者", key: "contactPerson" },
  { label: "主要領域", key: "primaryDomain" },
  { label: "自社営業担当", key: "salesPerson" },
  {
    label: "ランク",
    key: "rank",
    render: (row) => <RankLabelComponent rank={row.rank} />,
  },
  { label: "操作", key: "id" },
];

export const mockCompanyRows: CompanyTableRow[] = [
  {
    id: 1,
    clientName: "株式会社テックソリューション",
    contactPerson: "山田 太郎",
    primaryDomain: "Java",
    salesPerson: "佐藤 花子",
    rank: "A",
  },
  {
    id: 2,
    clientName: "デジタルイノベーション株式会社",
    contactPerson: "鈴木 一郎",
    primaryDomain: "React",
    salesPerson: "田中 美咲",
    rank: "B",
  },
  {
    id: 3,
    clientName: "クラウドシステムズ株式会社",
    contactPerson: "高橋 健太",
    primaryDomain: "AWS",
    salesPerson: "伊藤 直樹",
    rank: "C",
  },
  {
    id: 4,
    clientName: "ネクストウェーブ株式会社",
    contactPerson: "中村 翔",
    primaryDomain: "Python",
    salesPerson: "佐藤 花子",
    rank: "A",
  },
  {
    id: 5,
    clientName: "スマートデータ株式会社",
    contactPerson: "小林 美咲",
    primaryDomain: "Go",
    salesPerson: "田中 美咲",
    rank: "B",
  },
  {
    id: 6,
    clientName: "フューチャーリンク株式会社",
    contactPerson: "加藤 大輔",
    primaryDomain: "Vue",
    salesPerson: "伊藤 直樹",
    rank: "C",
  },
  {
    id: 7,
    clientName: "オリエンタルソフト株式会社",
    contactPerson: "吉田 彩",
    primaryDomain: "Java / Spring",
    salesPerson: "佐藤 花子",
    rank: "A",
  },
  {
    id: 8,
    clientName: "ブルーオーシャン株式会社",
    contactPerson: "山本 健",
    primaryDomain: "React / TypeScript",
    salesPerson: "田中 美咲",
    rank: "B",
  },
  {
    id: 9,
    clientName: "サンライズテック株式会社",
    contactPerson: "松本 裕子",
    primaryDomain: "AWS / Terraform",
    salesPerson: "伊藤 直樹",
    rank: "A",
  },
  {
    id: 10,
    clientName: "グローバルワークス株式会社",
    contactPerson: "井上 誠",
    primaryDomain: "PHP / Laravel",
    salesPerson: "佐藤 花子",
    rank: "C",
  },
  {
    id: 11,
    clientName: "アステリアシステムズ株式会社",
    contactPerson: "木村 玲奈",
    primaryDomain: "Kotlin",
    salesPerson: "田中 美咲",
    rank: "B",
  },
  {
    id: 12,
    clientName: "ハイパフォーマンス株式会社",
    contactPerson: "林 拓也",
    primaryDomain: "C# /.NET",
    salesPerson: "伊藤 直樹",
    rank: "A",
  },
  {
    id: 13,
    clientName: "コードクラフト株式会社",
    contactPerson: "斎藤 真由",
    primaryDomain: "Flutter",
    salesPerson: "佐藤 花子",
    rank: "B",
  },
  {
    id: 14,
    clientName: "データブリッジ株式会社",
    contactPerson: "清水 剛",
    primaryDomain: "Scala",
    salesPerson: "田中 美咲",
    rank: "C",
  },
  {
    id: 15,
    clientName: "イノベートラボ株式会社",
    contactPerson: "森 恵",
    primaryDomain: "Node.js",
    salesPerson: "伊藤 直樹",
    rank: "A",
  },
  {
    id: 16,
    clientName: "プライムパートナーズ株式会社",
    contactPerson: "池田 亮",
    primaryDomain: "Ruby on Rails",
    salesPerson: "佐藤 花子",
    rank: "B",
  },
  {
    id: 17,
    clientName: "セキュアネット株式会社",
    contactPerson: "橋本 優",
    primaryDomain: "セキュリティ",
    salesPerson: "田中 美咲",
    rank: "A",
  },
  {
    id: 18,
    clientName: "モバイルファースト株式会社",
    contactPerson: "石川 奈々",
    primaryDomain: "Swift",
    salesPerson: "伊藤 直樹",
    rank: "C",
  },
  {
    id: 19,
    clientName: "クラウドネイティブ株式会社",
    contactPerson: "前田 浩二",
    primaryDomain: "Kubernetes",
    salesPerson: "佐藤 花子",
    rank: "B",
  },
  {
    id: 20,
    clientName: "エクスペリエンスデザイン株式会社",
    contactPerson: "藤原 里奈",
    primaryDomain: "UI/UX",
    salesPerson: "田中 美咲",
    rank: "A",
  },
  {
    id: 21,
    clientName: "アナリティクスワン株式会社",
    contactPerson: "岡田 智也",
    primaryDomain: "データ分析",
    salesPerson: "伊藤 直樹",
    rank: "B",
  },
  {
    id: 22,
    clientName: "ディープラーニング研究所",
    contactPerson: "長谷川 萌",
    primaryDomain: "機械学習",
    salesPerson: "佐藤 花子",
    rank: "A",
  },
  {
    id: 23,
    clientName: "エンタープライズソリューションズ",
    contactPerson: "村上 健太",
    primaryDomain: "SAP",
    salesPerson: "田中 美咲",
    rank: "C",
  },
  {
    id: 24,
    clientName: "オープンソースジャパン株式会社",
    contactPerson: "近藤 あかり",
    primaryDomain: "Linux",
    salesPerson: "伊藤 直樹",
    rank: "B",
  },
];
